"use client";

import { SetStateAction, useMemo, useState } from "react";
import { usePacing } from "./usePacing";

import type {
  Level,
  Velocity,
  Confidence,
} from "./types";

import {
  Copy,
  CopyCheck,
  Share2,
  TrendingUp,
  TrendingDown,
  Pause,
  CalendarDays,
  Activity,
  Wallet,
  CircleDollarSign,
  Gauge,
  IndianRupee,
  Coins,
  PiggyBank,
} from "lucide-react";

export default function PacingTool() {

  /* =========================================================
      INPUT STATE
  ========================================================= */

  const [totalBudget, setTotalBudget] =
    useState<number | "">(50000);

  const [spentSoFar, setSpentSoFar] =
    useState<number | "">(18000);

  const [flightStart, setFlightStart] =
    useState("");

  const [flightEnd, setFlightEnd] =
    useState("");

  const [ctrLevel, setCtrLevel] =
    useState<Level>("HIGH");

  const [cpaLevel, setCpaLevel] =
    useState<Level>("MEDIUM");

  const [signalVelocity, setSignalVelocity] =
    useState<Velocity>("ACCELERATING");

  const [signalConfidence, setSignalConfidence] =
    useState<Confidence>("HIGH");

  const [copied, setCopied] =
    useState(false);

  /* =========================================================
      DERIVED DAYS
  ========================================================= */

  const totalDays = useMemo(() => {

    if (!flightStart || !flightEnd)
      return 0;

    const start =
      new Date(flightStart).getTime();

    const end =
      new Date(flightEnd).getTime();

    return Math.max(
      1,
      Math.ceil(
        (end - start) /
          (1000 * 60 * 60 * 24)
      ) +1
    );

  }, [flightStart, flightEnd]);

  /* =========================================================
      ENGINE
  ========================================================= */

  const result = usePacing({
    totalBudget:
      Number(totalBudget) || 0,

    totalDays,

    spentSoFar:
      Number(spentSoFar) || 0,

    ctrLevel,
    cpaLevel,

    signalVelocity,
    signalConfidence,

    flightStart,
    flightEnd,
  });

  /* =========================================================
      COPY
  ========================================================= */

  const copySummary = async () => {

    const text = `
MyAdBreak — Signal-Aware Pacing Recommendation

Direction: ${result.action}

Recommended Daily Spend: ₹${result.recommendedDailySpend.toFixed(0)} / day

Budget Shift: ${result.adjustmentPercent > 0 ? "+" : ""}${result.adjustmentPercent.toFixed(0)}%

Current Delivery Pace: ${(result.pacing * 100).toFixed(0)}%

Reasoning: ${result.reasoning.join(", ")}

Generated by myadbreak.com
`;

    await navigator.clipboard.writeText(
      text
    );

    setCopied(true);

    setTimeout(() => {
      setCopied(false);
    }, 2500);

  };

  /* =========================================================
      SHARE
  ========================================================= */

  const shareSummary = async () => {

    if (!navigator.share) return;

    await navigator.share({
      title:
        "MyAdBreak Pacing Recommendation",

      text: `

Recommendation: ${result.recommendation}

Recommended Daily Spend: ₹${result.recommendedDailySpend.toFixed(0)} / day

Budget Shift: ${result.adjustmentPercent > 0 ? "+" : ""}${result.adjustmentPercent.toFixed(0)}%

Current Delivery Pace: ${(result.pacing * 100).toFixed(0)}%

Reasoning: ${result.reasoning.join(", ")}

Key Signals:
• CTR Momentum: ${ctrLevel}
• CPA Efficiency: ${cpaLevel}
• Signal Velocity: ${signalVelocity.replace("_", " ")}
• Confidence Level: ${signalConfidence}

Generated via MyAdBreak Signal Intelligence

myadbreak.com
      `,
    });

  };

  /* =========================================================
      TONES
  ========================================================= */

  const tone =
    result.action === "SCALE"
      ? {
          bg: "bg-emerald-500",
          soft: "bg-emerald-50",
          text: "text-emerald-700",
          border: "border-emerald-200",
          icon: (
            <TrendingUp
              size={16}
            />
          ),
          title:
            "Increase Delivery",
        }

      : result.action === "REDUCE"
      ? {
          bg: "bg-red-500",
          soft: "bg-red-50",
          text: "text-red-600",
          border: "border-red-200",
          icon: (
            <TrendingDown
              size={16}
            />
          ),
          title:
            "Pull Back Spend",
        }

      : {
          bg: "bg-blue-500",
          soft: "bg-blue-50",
          text: "text-blue-700",
          border: "border-blue-200",
          icon: (
            <Pause
              size={16}
            />
          ),
          title:
            "Hold Current Pace",
        };

  /* =========================================================
      HUMAN INSIGHT
  ========================================================= */

const pacingExplanation =
  result.pacing < 0.9
    ? "Delivery is slower than planned. Gradual scaling may help recover pacing efficiently."

    : result.pacing > 1.1
    ? "Spend are running ahead of plan and may require moderation to avoid budget exhaustion."

    : "Delivery is tracking close to the planned pacing trajectory.";

  return (

    <div
      className="
        w-full
        max-w-6xl
        mx-auto

        grid
        lg:grid-cols-[380px_1fr]

        gap-4
        items-start
      "
    >

      {/* =====================================================
          LEFT PANEL
      ===================================================== */}

      <div
        className="
          rounded-2xl
          border
          border-gray-200
          bg-white

          p-5

          space-y-5
        "
      >

        {/* HEADER - LEFT PANE */}

        <div>

          <p
            className="
              text-[11px]
              uppercase
              tracking-[0.18em]
              text-blue-500
              font-semibold
            "
          >
            MyAdBreak Tools
          </p>

          <h2
            className="
              mt-2
              text-2xl
              font-semibold
              tracking-tight
              text-gray-900
            "
          >
            Signal-Aware Ad Pacing
          </h2>

          <p
            className="
              mt-2
              text-sm
              text-gray-600
              leading-relaxed
            "
          >
            Budget pacing recommendations based on delivery pressure,
            campaign efficiency, and signal momentum.
          </p>

        </div>

        {/* CAMPAIGN SETUP */}

        <div className="space-y-4">

          <SectionTitle
            title="Campaign Setup"
          />

          <div className="space-y-3">

            {/* BUDGET */}

            <InputField
              label="Total Budget"
              icon={
                <PiggyBank size={16} />
              }
              value={totalBudget}
              onChange={(e: { target: { value: string; }; }) =>
                setTotalBudget(
                  e.target.value === ""
                    ? ""
                    : Number(
                        e.target.value
                      )
                )
              }
              placeholder="50000"
            />

            {/* SPENT */}

            <InputField
              label="Spend So Far"
              icon={
                <Coins
                  size={16}
                />
              }
              value={spentSoFar}
              onChange={(e: { target: { value: string; }; }) =>
                setSpentSoFar(
                  e.target.value === ""
                    ? ""
                    : Number(
                        e.target.value
                      )
                )
              }
              placeholder="18000"
            />

            {/* DATES */}

            <div className="grid grid-cols-2 gap-3">

              <DateField
                label="Flight Start"
                value={flightStart}
                onChange={(e: { target: { value: SetStateAction<string>; }; }) =>
                  setFlightStart(
                    e.target.value
                  )
                }
              />

              <DateField
                label="Flight End"
                value={flightEnd}
                onChange={(e: { target: { value: SetStateAction<string>; }; }) =>
                  setFlightEnd(
                    e.target.value
                  )
                }
              />

            </div>

          </div>

        </div>

        {/* PERFORMANCE */}

        <div className="space-y-4">

          <SectionTitle
            title="Performance Signals"
          />

          <SegmentSelector
            label="CTR Momentum"
            value={ctrLevel}
            onChange={setCtrLevel}
            options={[
              "LOW",
              "MEDIUM",
              "HIGH",
            ]}
          />

          <SegmentSelector
            label="CPA Efficiency"
            value={cpaLevel}
            onChange={setCpaLevel}
            options={[
              "LOW",
              "MEDIUM",
              "HIGH",
            ]}
          />

          <SegmentSelector
            label="Signal Velocity"
            value={signalVelocity}
            onChange={
              setSignalVelocity
            }
            options={[
              "EMERGING",
              "ACCELERATING",
              "STABLE",
              "DECLINING",
            ]}
          />

          <SegmentSelector
            label="Signal Confidence"
            value={
              signalConfidence
            }
            onChange={
              setSignalConfidence
            }
            options={[
              "LOW",
              "MEDIUM",
              "HIGH",
            ]}
          />

        </div>

      </div>

      {/* =====================================================
          RIGHT PANEL
      ===================================================== */}

      <div
        className="
          lg:sticky
          lg:top-6
        
          rounded-2xl
          border
          border-gray-200
          bg-white

          overflow-hidden
        "
      >

        {/* =================================================
            TOP SUMMARY
        ================================================= */}

        <div className="p-6">

          <div className="flex items-start justify-between gap-4 flex-wrap">

            {/* LEFT */}

            <div>

              <h2
          className="
            mt-2
            text-2xl
            leading-tight
            font-semibold
            tracking-tight
            text-gray-900
          "
        >
          {result.action === "SCALE"
            ? "Performance supports higher delivery"
            : result.action === "REDUCE"
            ? "Delivery efficiency needs correction"
            : "Campaign pacing looks balanced"}
        </h2>

              <h3
                className="
                  mt-4
                  text-4xl
                  font-semibold
                  tracking-tight
                  text-gray-900
                "
              >
                ₹
                {result.recommendedDailySpend.toFixed(
                  0
                )}
                <span
                  className="
                    text-lg
                    font-medium
                    text-gray-400
                    ml-1
                  "
                >
                  / day
                </span>
              </h3>

              <p
                className="
                  mt-3
                  text-sm
                  text-gray-600
                  leading-relaxed
                  max-w-xl
                "
              >
                {
                  result.recommendation
                }
              </p>

              </div>
              <div>

                <div className={`
                  inline-flex
                  items-center
                  gap-2
                  mt-2
                  rounded-full

                  px-3 py-1.5

                  text-xs
                  font-medium

                  ${tone.soft}
                  ${tone.text}
                `}
              >

                {tone.icon}

                {tone.title}

              </div>

            </div>

            {/* RIGHT */}
{/* =================================================
    DELIVERY CONTEXT ROW
================================================= */}

<div
  className="
    grid
    md:grid-cols-3

    border-t
    border-gray-100

    bg-gray-50/70
  "
>

  {/* FLIGHT DURATION */}

  <div
    className="
      flex
      items-start
      gap-4

      px-5
      py-4
    "
  >

    <div
      className="
        mt-0.5

        flex
        h-10
        w-10
        shrink-0
        items-center
        justify-center

        rounded-xl

        bg-white
        border
        border-gray-200

        text-gray-600
      "
    >
      <CalendarDays size={18} />
    </div>

    <div>

      <p
        className="
          text-[11px]
          uppercase
          tracking-wide
          text-gray-400
        "
      >
        Flight Duration
      </p>

      <p
        className="
          mt-1
          text-base
          font-semibold
          text-gray-900
        "
      >
        {totalDays} Days
      </p>

      <p
        className="
          mt-1
          text-xs
          leading-relaxed
          text-gray-500
        "
      >
        Total campaign delivery window.
      </p>

    </div>

  </div>

  {/* IDEAL SPEND */}

  <div
    className="
      flex
      items-start
      gap-4

      border-t
      md:border-t-0
      md:border-l

      border-gray-100

      px-5
      py-4
    "
  >

    <div
      className="
        mt-0.5

        flex
        h-10
        w-10
        shrink-0
        items-center
        justify-center

        rounded-xl

        bg-white
        border
        border-gray-200

        text-gray-600
      "
    >
      <Wallet size={18} />
    </div>

    <div>

      <p
        className="
          text-[11px]
          uppercase
          tracking-wide
          text-gray-400
        "
      >
        Ideal Spend Pace
      </p>

      <p
        className="
          mt-1
          text-base
          font-semibold
          text-gray-900
        "
      >
        ₹
        {result.idealDailySpend.toFixed(
          0
        )}

        <span
          className="
            ml-1
            text-sm
            font-medium
            text-gray-400
          "
        >
          /day
        </span>

      </p>

      <p
        className="
          mt-1
          text-xs
          leading-relaxed
          text-gray-500
        "
      >
        Recommended baseline delivery rate.
      </p>

    </div>

  </div>

  {/* CURRENT SPEND */}

  <div
    className="
      flex
      items-start
      gap-4

      border-t
      md:border-t-0
      md:border-l

      border-gray-100

      px-5
      py-4
    "
  >

    <div
      className="
        mt-0.5

        flex
        h-10
        w-10
        shrink-0
        items-center
        justify-center

        rounded-xl

        bg-white
        border
        border-gray-200

        text-gray-600
      "
    >
      <Activity size={18} />
    </div>

    <div>

      <p
        className="
          text-[11px]
          uppercase
          tracking-wide
          text-gray-400
        "
      >
        Current pace
      </p>

      <p
        className="
          mt-1
          text-base
          font-semibold
          text-gray-900
        "
      >
        ₹
        {result.actualDailySpend.toFixed(
          0
        )}

        <span
          className="
            ml-1
            text-sm
            font-medium
            text-gray-400
          "
        >
          /day
        </span>

      </p>

      <p
        className="
          mt-1
          text-xs
          leading-relaxed
          text-gray-500
        "
      >
        Live spend velocity based on delivery.
      </p>

    </div>

  </div>

</div>

          </div>

        </div>


      {/* =================================================
    DELIVERY SNAPSHOT METRICS
================================================= */}

<div className="px-4 sm:px-6 pb-4">

  <div
    className="
      overflow-hidden

      rounded-2xl
      border
      border-gray-200

      bg-white
    "
  >

    {/* PRIMARY ROW */}

    <div
      className="
        flex
        flex-col
        gap-5

        px-4
        py-5

        sm:px-5

        lg:flex-row
        lg:items-start
        lg:justify-between

        bg-white
      "
    >

      {/* LEFT */}

      <div className="max-w-lg min-w-0">

        <p
          className="
            text-[11px]
            font-medium
            uppercase
            tracking-[0.18em]
            text-gray-400
          "
        >
          Delivery Snapshot
        </p>

        <h4
          className="
            mt-2

            text-lg
            leading-snug
            font-semibold
            tracking-tight
            text-gray-900
          "
        >

          {result.pacing < 0.9
            ? "Campaign is pacing behind target."
            : result.pacing > 1.1
            ? "Campaign is spending ahead of plan."
            : "Campaign pacing is currently balanced."}

        </h4>

        <p
          className="
            mt-2

            text-sm
            leading-relaxed
            text-gray-600
          "
        >
          {pacingExplanation}
        </p>

      </div>

      {/* RIGHT */}

      <div className="w-full lg:w-1/2 lg:shrink-0">

        <div
          className={`
            relative

            overflow-hidden

            rounded-2xl
            border

            px-4
            py-4

            ${
              result.pacing < 0.9
                ? `
                  border-amber-200
                  bg-amber-50/80
                `
                : result.pacing > 1.1
                ? `
                  border-red-200
                  bg-red-50/80
                `
                : `
                  border-emerald-200
                  bg-emerald-50/80
                `
            }
          `}
        >

          {/* GLOW */}

          <div
            className={`
              absolute
              -right-6
              -top-6

              h-20
              w-20

              rounded-full
              blur-2xl

              opacity-40

              ${
                result.pacing < 0.9
                  ? "bg-amber-300"
                  : result.pacing > 1.1
                  ? "bg-red-300"
                  : "bg-emerald-300"
              }
            `}
          />

          {/* TOP */}

          <div
            className="
              relative
              z-10

              flex
              items-start
              justify-between
              gap-4
            "
          >

            <div>

              <p
                className="
                  text-[10px]
                  uppercase
                  tracking-[0.18em]
                  text-gray-500
                "
              >
                Pacing Health
              </p>

              <div
                className="
                  mt-2

                  flex
                  items-end
                  gap-1.5
                "
              >

                <p
                  className={`
                    text-3xl
                    leading-none
                    font-semibold
                    tracking-tight

                    ${
                      result.pacing < 0.9
                        ? "text-amber-600"
                        : result.pacing > 1.1
                        ? "text-red-600"
                        : "text-emerald-600"
                    }
                  `}
                >
                  {(result.pacing * 100).toFixed(0)}%
                </p>

                 <span
                className="
                  mb-1

                  text-xs
                  font-medium
                  text-gray-400
                "
              >
                aligned
              </span>

              </div>

            </div>

            {/* ICON */}

            <div
              className={`
                flex
                h-10
                w-10
                shrink-0
                items-center
                justify-center

                rounded-xl

                ${
                  result.pacing < 0.9
                    ? `
                      bg-amber-100
                      text-amber-600
                    `
                    : result.pacing > 1.1
                    ? `
                      bg-red-100
                      text-red-600
                    `
                    : `
                      bg-emerald-100
                      text-emerald-600
                    `
                }
              `}
            >

              {result.pacing < 0.9 ? (
                <TrendingDown size={18} />
              ) : result.pacing > 1.1 ? (
                <Activity size={18} />
              ) : (
                <Gauge size={18} />
              )}

            </div>

          </div>

          {/* STATUS */}

          <div
            className="
              relative
              z-10

              mt-4

              border-t
              border-white/60

              pt-3
            "
          >

            <div
              className="
                flex
                items-center
                justify-between
                gap-3
              "
            >

              <div>

                <p
                  className={`
                    text-sm
                    font-semibold

                    ${
                      result.pacing < 0.9
                        ? "text-amber-700"
                        : result.pacing > 1.1
                        ? "text-red-700"
                        : "text-emerald-700"
                    }
                  `}
                >

                  {result.pacing < 0.9
                    ? "Behind Pace"
                    : result.pacing > 1.1
                    ? "High Spend Velocity"
                    : "Healthy Delivery"}

                </p>

                <p
                  className="
                    mt-1

                    text-xs
                    leading-relaxed
                    text-gray-500
                  "
                >

                  {result.pacing < 0.9
                    ? "Delivery needs acceleration."
                    : result.pacing > 1.1
                    ? "Budget is moving faster than planned."
                    : "Spend distribution remains stable."}

                </p>

              </div>

            </div>

          </div>

        </div>

      </div>

    </div>

  </div>

</div>
        {/* =================================================
            SIGNAL BREAKDOWN
        ================================================= */}

        <div className="px-6 pb-6">

          <div
            className="
              rounded-2xl
              border
              border-gray-200

              p-5
            "
          >

            <p
              className="
                text-[11px]
                uppercase
                tracking-[0.18em]
                text-gray-500
                font-medium
              "
            >
              Decision Factors
            </p>

            <div
              className="
                mt-4
                space-y-3
              "
            >

              {result.reasoning.map(
                (r, i) => (

                  <div
                    key={i}
                    className="
                      flex
                      items-start
                      gap-3
                    "
                  >

                    {/* HEAT BAR */}

                    <span
                      className={`
                        mt-1

                        h-4
                        w-1.5

                        rounded-full
                        shrink-0

                        ${tone.bg}
                      `}
                    />

                    <p
                      className="
                        text-[13px]
                        leading-relaxed
                        text-gray-700
                      "
                    >
                      {r}
                    </p>

                  </div>

                )
              )}

            </div>

          </div>

        </div>

        {/* =================================================
            FOOTER
        ================================================= */}

        <div
          className="
            border-t
            border-gray-200

            px-6 py-4

            flex
            items-center
            justify-between

            flex-wrap
            gap-4
          "
        >

          {/* CREDIT */}

          <div
            className="
              text-xs
              text-gray-500
            "
          >
            Generated via
            MyAdBreak Signal Intelligence
          </div>

          {/* ACTIONS */}

          <div
            className="
              flex
              items-center
              gap-2
            "
          >

            {/* COPY */}

            <button
              onClick={copySummary}
              className="
                inline-flex
                items-center
                gap-2

                rounded-full

                border
                border-gray-200

                bg-white

                px-4 py-2

                text-xs
                font-medium

                text-gray-700

                hover:bg-gray-50

                transition-all

                active:scale-[0.98]
              "
            >

              {copied ? (
                <>
                  <CopyCheck
                    size={14}
                  />
                  Copied
                </>
              ) : (
                <>
                  <Copy size={14} />
                  Copy Summary
                </>
              )}

            </button>

            {/* SHARE */}

            <button
              onClick={shareSummary}
              className="
                inline-flex
                items-center
                gap-2

                rounded-full

                border
                border-gray-200

                bg-white

                px-4 py-2

                text-xs
                font-medium

                text-gray-700

                hover:bg-gray-50

                transition-all

                active:scale-[0.98]
              "
            >

              <Share2
                size={14}
              />

              Share

            </button>

          </div>

        </div>

      </div>

    </div>
  );
}

/* =========================================================
    SECTION TITLE
========================================================= */

function SectionTitle({
  title,
}: {
  title: string;
}) {

  return (

    <p
      className="
        text-[11px]
        uppercase
        tracking-[0.18em]
        text-gray-500
        font-medium
      "
    >
      {title}
    </p>

  );
}

/* =========================================================
    INPUT FIELD
========================================================= */

function InputField({
  label,
  icon,
  value,
  onChange,
  placeholder,
}: any) {

  return (

    <div>

      <label
        className="
          mb-1.5
          flex
          items-center
          gap-2

          text-xs
          text-gray-500
        "
      >

        {icon}

        {label}

      </label>

      <input
        type="number"
        value={value}
        onChange={onChange}
        placeholder={placeholder}
        className="
          w-full

          rounded-xl

          border
          border-gray-200

          bg-white

          px-4 py-3

          text-sm
          text-gray-900

          outline-none

          focus:border-blue-500
        "
      />

    </div>

  );
}

/* =========================================================
    DATE FIELD
========================================================= */

function DateField({
  label,
  value,
  onChange,
}: any) {

  return (

    <div>

      <label
        className="
          mb-1.5
          flex
          items-center
          gap-2

          text-xs
          text-gray-500
        "
      >

        <CalendarDays
          size={14}
        />

        {label}

      </label>

      <input
        type="date"
        value={value}
        onChange={onChange}
        className="
          w-full

          rounded-xl

          border
          border-gray-200

          bg-white

          px-4 py-3

          text-sm
          text-gray-900

          outline-none

          focus:border-blue-500
        "
      />

    </div>

  );
}

/* =========================================================
    SEGMENT SELECTOR
========================================================= */

function SegmentSelector({
  label,
  value,
  onChange,
  options,
}: {
  label: string;
  value: string;
  onChange: (v: any) => void;
  options: string[];
}) {

  return (

    <div>

      <p
        className="
          mb-2
          text-xs
          text-gray-500
        "
      >
        {label}
      </p>

      <div
        className="
          flex
          flex-wrap
          gap-2
        "
      >

        {options.map((option) => (

          <button
            key={option}
            onClick={() =>
              onChange(option)
            }
            className={`
              rounded-full

              px-3 py-2

              text-xs
              font-medium

              transition-all

              ${
                value === option
                  ? `
                    bg-blue-500
                    text-white
                  `
                  : `
                    bg-gray-100
                    text-gray-600
                    hover:bg-gray-200
                  `
              }
            `}
          >

            {option.replace(
              "_",
              " "
            )}

          </button>

        ))}

      </div>

    </div>

  );
}

/* =========================================================
    MINI METRIC
========================================================= */

function MiniMetric({
  icon,
  label,
  value,
}: any) {

  return (

    <div
      className="
        rounded-xl

        border
        border-gray-200

        bg-white

        px-3 py-3

        min-w-24
      "
    >

      <div
        className="
          flex
          items-center
          gap-1.5

          text-gray-400
        "
      >
        {icon}

        <span
          className="
            text-[10px]
            uppercase
            tracking-wide
          "
        >
          {label}
        </span>

      </div>

      <p
        className="
          mt-2
          text-sm
          font-semibold
          text-gray-900
        "
      >
        {value}
      </p>

    </div>

  );
}

/* =========================================================
    METRIC
========================================================= */

function Metric({
  label,
  value,
  style,
}: {
  label: string;
  value: string;
  style: string;
}) {

  return (

    <div
      className={`
        px-4 py-4
        ${style}
      `}
    >

      <p
        className="
          text-[10px]
          uppercase
          tracking-wide
          opacity-70
        "
      >
        {label}
      </p>

      <p
        className="
          mt-2
          text-lg
          font-semibold
        "
      >
        {value}
      </p>

    </div>

  );
}